import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SchoolHub",
  description: "Generated by OrangeCode",
};

export default async function RootLayout({ children }) {

  const resp = await fetch('http://localhost:9999/topics')
  const topics = await resp.json();
  


  return (
    <html>
      <body>
        <h1><Link href="/">WEB</Link></h1>
      <ol>
        {topics.map((topic)=>{
          return <li key={topic.id}><Link href='/read/${topic.id}'>{topic.title}</Link></li>
        })}
      </ol>
      
      
      <ol>
        <li><Link href="/read/1">html</Link></li>
        <li><Link href="/read/2">css</Link></li>
      </ol>
   
        {children}
   
      <ul>
        <li><Link href="/create">Create</Link></li>
        <li><Link href="/update">Update</Link></li>
        <li><input type="button" value="delete"/> </li>
      </ul>
      
      </body>
    </html>
  );
}
